### ISSUE TITLE
Production build failes

### ISSUE THREAD

**Issue by danieldoinov** [toni-rmc/laravel-angular-integration#7]
First I must say: great project. 
Your documents and build scripts saved me a lot of time and work. Thank you!

The issue i have to report is this :
 while the dev build works great the production build script fails. 
I have looked for a fix and nothing i have found so far worked for me. I would guess that its something related to the new angular-cli versions, because everywhere i look they say update your client. 

interestingly enough "ng build --prod" goes without any errors. 

Here is the error : 
```
Version: webpack 3.8.1
Time: 10684ms
 17 assets
[6GLz] ./src/$$_gendir lazy 160 bytes {2} [built]
[DuR2] (webpack)/buildin/global.js 488 bytes {0} {3} [built]
[OE0E] ./node_modules/@angular/platform-browser/esm5/platform-browser.js + 1 modules 381 kB {3} [built]
[XS25] ./src/polyfills.ts 2.75 kB {0} [built]
[qOWO] ./src/styles.css 41 bytes {1} [built]
[x35b] ./src/main.ts + 1 modules 558 bytes {2} [built]
   [0] multi ./src/main.ts 28 bytes {2} [built]
   [1] multi ./src/polyfills.ts 28 bytes {0} [built]
   [2] multi ./node_modules/font-awesome/css/font-awesome.min.css ./node_modules/primeng/resources/themes/omega/theme.css ./node_modules/primeng/resources/primeng.min.css ./src/styles.css 64 bytes {1} [built]
    + 146 hidden modules

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'D:\xampp\htdocs\MorphologicalBox\angular-integration\MBox\src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts

ERROR in Error: Please update @angular/cli. Angular 5+ requires at least Angular CLI 1.5+
    at throwNotSupportedError (D:\xampp\htdocs\MorphologicalBox\angular-integration\MBox\node_modules\@angular\compiler-cli\src\ngtools_api.js:78:11)
    at Function.NgTools_InternalApi_NG_2.codeGen (D:\xampp\htdocs\MorphologicalBox\angular-integration\MBox\node_modules\@angular\compiler-cli\src\ngtools_api.js:31:15)
    at _donePromise.Promise.resolve.then (D:\xampp\htdocs\MorphologicalBox\angular-integration\MBox\node_modules\@ngtools\webpack\src\plugin.js:430:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

And here is my dev environment:
```
Angular CLI: 1.6.7
Node: 8.9.4
OS: win32 x64
Angular: 5.0.1
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/animations: 5.2.1
@angular/cli: 1.6.7
@angular/material: 5.1.1
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack-concat-plugin: 1.4.0
webpack-dev-server: 2.9.4
webpack: 3.8.1 
```

I would appreciate any help you can provide. 
Thank you.

**Comment by toni-rmc** [comment]
When you want production build use:

`npm run build`
 not
`ng build`

Or you can use `ng build --prod`

But use the appropriate `webpack.config.js`  from `angular_apps_cli/webpack_config/prod` folder first.

**Comment by danieldoinov** [comment]
I finally figured out what was the problem and have created a pull request that fixes those issues. 
#8

**Comment by toni-rmc** [comment]
I have merged it with my master branch.
Thanks for figuring it out and solving it.
